version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: folias-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=folias_admin
      - MONGO_INITDB_ROOT_PASSWORD=folias_password
      - MONGO_INITDB_DATABASE=folias
    restart: unless-stopped

  # Optional MongoDB UI tool
  mongo-express:
    image: mongo-express
    container_name: folias-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=folias_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=folias_password
      - ME_CONFIG_MONGODB_URL=mongodb://folias_admin:folias_password@mongodb:27017/
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
    name: folias-mongodb-data 